# Generated by Django 3.1.2 on 2021-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(max_length=5000),
        ),
    ]
