# Generated by Django 3.1.2 on 2021-02-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210220_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-recipe_name']},
        ),
    ]
