# Generated by Django 3.1.2 on 2021-02-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_useremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmail',
        ),
    ]
