# Generated by Django 3.1.2 on 2021-02-21 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_delete_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
