# Generated by Django 3.1.2 on 2021-02-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210222_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
