# Generated by Django 3.1.2 on 2021-02-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
