# Generated by Django 3.1.2 on 2021-02-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
