# Generated by Django 3.1.2 on 2021-02-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
