# Generated by Django 3.1.2 on 2021-02-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Rate',
        ),
    ]
