# Generated by Django 3.1.2 on 2021-02-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_auto_20210226_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='mark',
            new_name='rating',
        ),
    ]
