# Generated by Django 3.1.2 on 2021-02-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20210226_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='rate',
        ),
    ]
